#!/usr/bin/env bash
# Displays DNS record info for subdomains of a domain

# Function to fetch and print record info
print_domain_subdomain(){
    dig "$1" | grep -A1 'ANSWER SECTION' | sed -r "s/$1./$2/g" | awk -f"" ' NR==2 { print "The subdomain" $1 "is a "record and points to "$5}'
}

if [ "$#" -eq 2]
then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1 "www"
    print_domain_subdomain "web-01.$1 "www"
    print_domain_subdomain "web-02.$1" "www"
fi
