#!/usr/bin/env bash
# Displays DNS information for specified domain and subdomains

get_dns_record() {
    local domain=$1
    local subdomain=$2
    local result
    
    result=$(dig "$subdomain.$domain" +short | awk '{print $1}')
    if [ -n "$result" ]; then
        echo "The subdomain $subdomain is a A record and points to $result"
    fi
}

main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        get_dns_record "$domain" "www"
        get_dns_record "$domain" "lb-01"
        get_dns_record "$domain" "web-01"
        get_dns_record "$domain" "web-02"
    else
        get_dns_record "$domain" "$subdomain"
    fi
}

main "$@"
