#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

# Check if fewer than 4 arguments are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

# Check if the file exists before transferring
if [ ! -f "$FILE" ]; then
    echo "Error: File '$FILE' not found!"
    exit 2
fi

# Run scp with private key and strict host key checking disabled
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
