#!/usr/bin/env bash
# Script that transfers a file to a server using SCP

# Exit if incorrect number of arguments
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign args to vars
FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Check if the file exists
if [ ! -f "$FILE" ]; then
    echo "Error: File '$FILE' not found"
    exit 2
fi

# Use scp to transfer file with strict host key checking disabled
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "${USERNAME}@${SERVER_IP}:~/"
