#!/usr/bin/env bash
# Script to install nginx and serve a Hello World! page

# Exit on error
set -e

# Update and install nginx silently
apt-get update -y > /dev/null
apt-get install nginx -y > /dev/null

# Overwrite the default Nginx index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart nginx using service
service nginx restart
