#!/usr/bin/env bash
# Script to configure a custom 404 page on an Nginx server

# Exit on error
set -e

# Update and install nginx
apt-get update -y > /dev/null
apt-get install nginx -y > /dev/null

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update nginx config to use custom 404 page
sed -i '/error_page 404/d' /etc/nginx/sites-available/default
sed -i '/^\s*server\s*{/,/^\s*}/ s/^\s*}/    error_page 404 \/custom_404.html;\n}/' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
