#!/usr/bin/env bash
# Configures Nginx on a new Ubuntu 16.04 server to add X-Served-By header, 404 page, and redirect

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create web root and files
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo sh -c "echo 'Ceci n\'est pas une page' > /var/www/html/404.html"

# Configure Nginx with X-Served-By header, 404 page, and redirect
sudo sed -i "s|server_name _;|server_name _;\n\tadd_header X-Served-By $(hostname);\n\trewrite ^/redirect_me https://www.bunnyenyash.com permanent;|" /etc/nginx/sites-enabled/default
sudo sed -i "s|listen 80 default_server;|listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}|" /etc/nginx/sites-enabled/default

# restart the web server after updating the settings
sudo service nginx restart
