#!/usr/bin/env bash
# Configures a new Ubuntu server with Nginx and a custom HTTP header X-Served-By

# Exit on error
set -e

# Install nginx
apt-get update -y > /dev/null
apt-get install nginx -y > /dev/null

# Set Hello World content
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Insert custom header using the system's hostname
# shellcheck disable=SC2154
sed -i "/listen 80 default_server;/a add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
