#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back

backend http_back
        balance roundrobin
        server 315123-web-01 18.208.150.193 check
	server 315123-web-02 35.170.191.53 check
"
echo "$server_config" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy service
service haproxy restart
